package domain;
// Generated 2018-2-20 17:30:58 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TMessage generated by hbm2java
 */
@Entity
@Table(name = "t_message", catalog = "law")
public class TMessage implements java.io.Serializable {

	private int id;
	
	private String name;

	public TMessage() {
	}

	public TMessage(int id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
}
